<?php
// Created via `gulp vars`. Defined in theme's manifest.js
add_theme_support( 'editor-color-palette', [
  [ 'name' => 'Primary', 
    'slug' => 'primary', 
    'color' => '#fe0700', 
  ],
  [ 'name' => 'Primary-dark', 
    'slug' => 'primary-dark', 
    'color' => '#a00700', 
  ],
  [ 'name' => 'Secondary', 
    'slug' => 'secondary', 
    'color' => '#d08a4e', 
  ],
  [ 'name' => 'Black', 
    'slug' => 'black', 
    'color' => '#000', 
  ],
  [ 'name' => 'Grey-dark', 
    'slug' => 'grey-dark', 
    'color' => '#333', 
  ],
  [ 'name' => 'Grey', 
    'slug' => 'grey', 
    'color' => '#777', 
  ],
  [ 'name' => 'Grey-light', 
    'slug' => 'grey-light', 
    'color' => '#bbb', 
  ],
  [ 'name' => 'Grey-extra-light', 
    'slug' => 'grey-extra-light', 
    'color' => '#eee', 
  ],
  [ 'name' => 'White', 
    'slug' => 'white', 
    'color' => '#fff', 
  ],
]);


